# Generated by Django 4.0.6 on 2024-04-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_folder_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
