# Generated by Django 4.0.6 on 2024-04-28 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_remove_image_tags_alter_image_description_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['user', 'created'], name='gallery_fol_user_id_5f734e_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['folder', 'created'], name='gallery_ima_folder__840c68_idx'),
        ),
    ]
